### ISSUE TITLE
Crash: net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by anoomolu** [gniftygnome/obtainable-end#2]
I've been experiencing crashes when completing the end portal frame, likely linked to the global sound. It's throwing a "net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads" message in the log. Can be reproduced by breaking and placing the final end portal frame needed to complete the structure a few times

https://mclo.gs/JVGJnE1 for the crash log.

**Comment by gniftygnome** [comment]
Seems pretty straight-forward.  Presumably I'm doing something on the wrong thread, although I think I copied vanilla...  Anyway I'll look into this.
