### ISSUE TITLE
Wither cages are super easy to make now

### ISSUE THREAD

**Issue by anoomolu** [gniftygnome/obtainable-end#4]
Hiya! Been using this mod for a while now, been working great!

One problem I noticed is that being able to craft End Portal Frames makes Wither cages super easy to make. To remove the block from the wither_immune tag, I had to override the vanilla tag, so I'm not sure how this would play with other mods that add to the tag.

If this is isn't something easily fixable then no worries, might be worth making a note somewhere that packmakers should manually adjust their wither_immune block tag via datapack.

**Comment by gniftygnome** [comment]
Ideally, Mojang would just give us a block-breaking block.  :P

I have updated Obtainable End to remove End Portal Frame blocks from the WITHER_IMMUNE tag by default (without replacing the tag), and added a configuration option (`frameIsWitherImmune`) to restore the vanilla behavior.

This update is in 1.0.3 for 1.20/1.20.1 and 1.1.3 for 1.20.2.
