### ISSUE TITLE
Backported to Minecraft 1.18.2

### ISSUE THREAD

**Issue by ScrewTSW** [gniftygnome/obtainable-end#5]
Hello.

I have a functional version (still may have stuff that needs to be cleaned up/removed) for Minecraft 1.18.2

I am able to craft the portal frames, place it in the world, it auto-aligns and I'm able to fill it with eyes of ender and create the portal.

Please if you'd like, create a new branch in your repository and open a PR from https://github.com/ScrewTSW/obtainable-end/tree/1.18

Functional release can be found at https://github.com/ScrewTSW/obtainable-end/releases/tag/1.1.3-fabric1.18.2

**Comment by gniftygnome** [comment]
Thanks.  I've made the PR.  It's got a few things I'll need to address to merge.  I'll look closer when I have some time.

**Comment by gniftygnome** [comment]
Undid the style changes, fixed configurable Wither immunity, restored proper recipe mod ID.
Tested features including fast breaking with pick-axe, wither immunity, sounds, recipe, etc.
I noticed the recipe advancement isn't working, but I think I'll let that be for now.

**Comment by ScrewTSW** [comment]
> Undid the style changes, fixed configurable Wither immunity, restored proper recipe mod ID.
> Tested features including fast breaking with pick-axe, wither immunity, sounds, recipe, etc.
> I noticed the recipe advancement isn't working, but I think I'll let that be for now.
> 

Perfect, thank you so much!
